export const SEGMENT_GET_REQUEST = "SEGMENT_GET_REQUEST";
export const SEGMENT_GET_SUCCESS = "SEGMENT_GET_SUCCESS";
export const SEGMENT_GET_FAIL = "SEGMENT_GET_FAIL";

export const SEGMENT_ID_GET_REQUEST = "SEGMENT_ID_GET_REQUEST";
export const SEGMENT_ID_GET_SUCCESS = "SEGMENT_ID_GET_SUCCESS";
export const SEGMENT_ID_GET_FAIL = "SEGMENT_ID_GET_FAIL";
